name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

  terdown:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checout@v2
      - name: Run a one-line script
        run: echo goodbye everyone
