name: continous integration
on:
  push:
    branches:
      - '**'
jobs:
  test_codebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: pytest